_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  WEIGHTS: /data/new/Experiments/jlgomez/cotraining_sem_seg/cityscapes_cotraining_270_deeplabV3_cbst_2_2_5k_wrong/model_A/3/checkpoints/model_0004999.pth #"detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  SEM_SEG_HEAD:
    IGNORE_VALUE: 19
    NUM_CLASSES: 20
DATASETS:
  TRAIN_IMG_TXT: /datatmp/Datasets/segmentation/cityscapes/leftimage8bit_subtrain_sup.txt
  TRAIN_GT_TXT: /datatmp/Datasets/segmentation/cityscapes/gtFine_subtrain_sup.txt
  TEST_IMG_TXT: /datatmp/Datasets/segmentation/cityscapes/leftimage8bit_val.txt
  TEST_GT_TXT: /datatmp/Datasets/segmentation/cityscapes/gtFine_val.txt
  LABELS: "cityscapes"
INPUT:
  ACTIVATE_MIN_SIZE_TRAIN: True
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: False
    TYPE: "absolute"
    SIZE: (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 1.0
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.002
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: /data/new/Experiments/jlgomez/detectron2baselines/cotraining_sem_seg/cityscapes_cotraining_270_deeplabV3_cbst_2_2_5k_wrong/eval
AUGMENTATION:
  CUTOUT: True
  CUTOUT_N_HOLES: (0, 1)
  CUTOUT_LENGTH: (300, 600)
  RANDOM_RESIZE: False
  RESIZE_RANGE: (0.5, 1.5)
  HFLIP: True
  HFLIP_PROB: 0.5
 
