_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  SEM_SEG_HEAD:
    IGNORE_VALUE: 255
    NUM_CLASSES: 20
DATASETS:
  TRAIN_IMG_TXT: /datatmp/Datasets/segmentation/GTA/gta5_rgb.txt
  TRAIN_GT_TXT: /datatmp/Datasets/segmentation/GTA/gta5_gt_cityscapes.txt
  TEST_IMG_TXT: /datatmp/Datasets/segmentation/cityscapes/leftimage8bit_val_debug.txt
  TEST_GT_TXT: /datatmp/Datasets/segmentation/cityscapes/gtFine_val_debug.txt
  LABELS: "cityscapes"
PSEUDOLABELING: 
  NUMBER: 10 # number of pseudolabels that will be added to the source dataset
  MODE: "mpt"
  COLLABORATION: "cotraining"
  ACCUMULATION: "update_best_score"
INPUT:
  FORMAT: "RGB"
  ACTIVATE_MIN_SIZE_TRAIN: True
  MIN_SIZE_TRAIN: (512, 768, 1024, 1280, 1536, 1792, 2048)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  RESIZED: True
  RESIZE_SIZE: (1024, 2048)
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 1.0
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.002
  STEPS: (10000, )
  MAX_ITER: 10
  CHECKPOINT_PERIOD: 10
TEST:
  EVAL_PERIOD: 10
OUTPUT_DIR: /data/new/Experiments/jlgomez/cotraining_sem_seg/debug
AUGMENTATION_A:
  CUTOUT: False
  CUTOUT_N_HOLES: (0, 1)
  CUTOUT_LENGTH: (300, 600)
  RANDOM_RESIZE: False
  RESIZE_RANGE: (0.5, 1.5)
  HFLIP: True
  HFLIP_PROB: 0.5
AUGMENTATION_B:
  CUTOUT: True
  CUTOUT_N_HOLES: (0, 1)
  CUTOUT_LENGTH: (300, 600)
  RANDOM_RESIZE: False
  RESIZE_RANGE: (0.5, 1.5)
  HFLIP: True
  HFLIP_PROB: 0.5
