_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  SEM_SEG_HEAD:
    IGNORE_VALUE: 255
    NUM_CLASSES: 20
DATASETS:
  TRAIN_IMG_TXT: /datatmp/Datasets/segmentation/GTA/gta5_rgb.txt
  TRAIN_GT_TXT: /datatmp/Datasets/segmentation/GTA/gta5_gt_cityscapes.txt
  TEST_IMG_TXT: /datatmp/Datasets/segmentation/cityscapes/leftimage8bit_val.txt
  TEST_GT_TXT: /datatmp/Datasets/segmentation/cityscapes/gtFine_val.txt
  LABELS: "cityscapes"
PSEUDOLABELING: 
  NUMBER: 100 # number of pseudolabels that will be added to the source dataset
  MODE: "cbst"
  COLLABORATION: "cotraining"
  ACCUMULATION: "update_best_score"
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.002
  STEPS: (10000, )
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: /data/new/Experiments/jlgomez/cotraining_sem_seg/testing_gta_cotraining_update_score_1k_incremental
AUGMENTATION_A:
  HFLIP: False
  HFLIP_PROB: 0.5
AUGMENTATION_B:
  CUTOUT: True
  CUTOUT_N_HOLES: 3
  CUTOUT_LENGTH: 300
  HFLIP: True
  HFLIP_PROB: 0.5
 
