_BASE_: Base-DeepLabV3-OS16-Semantic.yaml
MODEL:
  WEIGHTS: "detectron2://DeepLab/R-103.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
  RESNETS:
    DEPTH: 101
    NORM: "BN"
    RES5_MULTI_GRID: [1, 2, 4]
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
  SEM_SEG_HEAD:
    NAME: "DeepLabV3Head"
    NORM: "BN"
    IGNORE_VALUE: 19
    NUM_CLASSES: 20
DATASETS:
  TRAIN_IMG_TXT: /datatmp/Datasets/segmentation/cityscapes/leftimage8bit_subtrain_sup.txt
  TRAIN_GT_TXT: /datatmp/Datasets/segmentation/cityscapes/gtFine_subtrain_sup.txt
  TEST_IMG_TXT: /datatmp/Datasets/segmentation/cityscapes/leftimage8bit_subtrain_val.txt
  TEST_GT_TXT: /datatmp/Datasets/segmentation/cityscapes/gtFine_subtrain_val.txt
  LABELS: "cityscapes"
PSEUDOLABELING: 
  NUMBER: 150 # number of pseudolabels that will be added to the source dataset
  MODE: "cbst"
  COLLABORATION: "none"
  ACCUMULATION: "update_best_score"
INPUT:
  FORMAT: "RGB"
  ACTIVATE_MIN_SIZE_TRAIN: True
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  RESIZED: True
  RESIZE_SIZE: (1024, 2048)
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 1.0
SOLVER:
  ALTERNATE_SOURCE_PSEUDOLABELS: True
  SOURCE_PSEUDOLABELS_BATCH_RATIO: (2, 2) # ratio sum must match IMS_PER_BATCH, 1st values source batch size, second values target batch size
  IMS_PER_BATCH: 4
  BASE_LR: 0.00005
  STEPS: (10000, )
  MAX_ITER: 5000
  CHECKPOINT_PERIOD: 2500
TEST:
  EVAL_PERIOD: 2500
OUTPUT_DIR: /data/new/Experiments/jlgomez/cotraining_sem_seg/cityscapes_selftraining_deeplabv3_270_cbst_2_2_5k
AUGMENTATION_A:
  CUTOUT: False
  CUTOUT_N_HOLES: (0, 1)
  CUTOUT_LENGTH: (300, 600)
  RANDOM_RESIZE: False
  RESIZE_RANGE: (0.5, 1.5)
  HFLIP: True
  HFLIP_PROB: 0.5